spring:
  application:
    name: ms-menu

  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: appuser
    password: AppPass!123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
    drop-first: false

restaurant:
  service:
    url: http://localhost:8081

server:
  port: 8084
